repository:
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: false
  default_branch: main
  delete_branch_on_merge: true
  description: Julia & Rust Playground
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  homepage: ''
  name: Julia&Rust
  private: true
  topics: Julia & Rust Playground
